name: web-shortcuts
services:
  backend:
    build: ./backend
    volumes:
      - /DATA/AppData/web-shortcuts/data:/app/data
      - /DATA/AppData/web-shortcuts/upload:/app/upload
    restart: unless-stopped
    network_mode: bridge

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    network_mode: bridge